### ISSUE TITLE
Mozilla’s Recommended Extensions

### ISSUE THREAD

**Issue by pierluc-codes** [kemayo/firefox-sticky-containers#14]
Hi,

First, thanks a lot for your work! I cannot imagine using firefox without it.

Any hope to make it part of Mozilla’s Recommended Extensions program?

![Screen Shot 2020-07-27 at 6 32 49 AM](https://user-images.githubusercontent.com/155531/88532694-06f52680-cfd3-11ea-9a19-64bf79d77b5c.png)

**Comment by kemayo** [comment]
I think the only way to get into that program is for people to recommend it -- there's an email address mentioned at the bottom of https://support.mozilla.org/en-US/kb/recommended-extensions-program

**Comment by pierluc-codes** [comment]
I did and never got any answer or follow up :(
